### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by libliboom** [libliboom/TroubleShooting-archive-android#12]
Error:
2020-01-07 21:01:58.912 1943-2028/com.github.libliboom.wordbook E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.github.libliboom.wordbook, PID: 1943
    java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.onResponse(DefaultCallAdapterFactory.java:76)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.onResponse(DefaultCallAdapterFactory.java:76) 
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:129) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by libliboom** [comment]
[Solution]

add the following code build.gradle in app.
android {
    ...

    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
}

https://github.com/square/retrofit/issues/3043
