### ISSUE TITLE
Program type already present: com.google.protobuf.AnyProto

### ISSUE THREAD

**Issue by libliboom** [libliboom/TroubleShooting-archive-android#13]
[Log]
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.google.protobuf.AnyProto
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by libliboom** [comment]
[Solution]
First of all you should try to find duplicated library by a command with './gradlew dependencies'.
In my case, I edited the following library

Before)
implementation 'com.google.cloud:google-cloud-texttospeech:0.117.1-beta'

After)
implementation('com.google.cloud:google-cloud-texttospeech:0.117.1-beta', {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
})
