### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to create call adapter for io.reactivex.rxjava3.core.Observable

### ISSUE THREAD

**Issue by libliboom** [libliboom/TroubleShooting-archive-android#18]
### Log
```
java.lang.IllegalArgumentException: Unable to create call adapter for io.reactivex.rxjava3.core.Observable<com.github.libliboom.exchangerate.data.XRResponse>
        for method XRService.fetchLatest
        at retrofit2.Utils.methodError(Utils.java:54)
        at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:116)
        at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy1.fetchLatest(Unknown Source)
        at com.github.libliboom.exchangerate.net.XRServiceClient.fetch(XRServiceClient.kt:28)

```

**Comment by libliboom** [comment]
### Solution

Add below library.
```
implementation 'com.squareup.retrofit2:adapter-rxjava3:2.9.0
```

Then add `addCallAdapterFactory` method when retrofit be created.
```
retrofit = Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addCallAdapterFactory(RxJava3CallAdapterFactory.create())
            .addConverterFactory(GsonConverterFactory.create())
            .client(httpClient.build())
            .build()
```
